"""
tools/plan_section.py -- one plan section per branch, so parallel Claude
sessions never collide (docs/guides/PARALLEL-SESSIONS.md).

    python tools/plan_section.py new <slug> "<title>"   reserve the next 3.N: branch + worktree + file
    python tools/plan_section.py env [3.N]              this branch's ports, ROS domain, container, image, logs
    python tools/plan_section.py index                  regenerate the section index
    python tools/plan_section.py overlap                files this branch shares with other plan/* branches
    python tools/plan_section.py ready [--full]         rebase check + fast tier (or the full suite); records a pass
    python tools/plan_section.py gate <base> <sha>      the pre-push hook's check: docs only -> spec lint, else fast tier
    python tools/plan_section.py split                  one-time: PLAN-ros-alignment.md's 3.N sections -> files

Sections live in `docs/plans/ros-alignment/<number>-<slug>.md`; the number is
reserved by the BRANCH NAME `plan/<number>-<slug>`. Worktrees share one .git,
so every session on this machine sees every branch, pushed or not, and git
refuses to create a branch that exists -- which makes `new` atomic.
"""

import os
import re
import subprocess
import sys

PLAN = "docs/plans/PLAN-ros-alignment.md"
DIR = "docs/plans/ros-alignment"
INDEX = f"{DIR}/README.md"
HEAD_RE = re.compile(r"^### (3\.(\d+)([a-z]?)) (.*)$")
FILE_RE = re.compile(r"^(3\.(\d+)([a-z]?))-(.+)\.md$")
BRANCH_RE = re.compile(r"plan/(3\.(\d+))-")
SECTIONS_START = "<!-- sections: generated by tools/plan_section.py index; do not edit -->"
SECTIONS_END = "<!-- /sections -->"


def git(*args, check=True, cwd=None) -> str:
    r = subprocess.run(["git", *args], capture_output=True, text=True, cwd=cwd)
    if check and r.returncode != 0:
        raise SystemExit(f"git {' '.join(args)}: {r.stderr.strip()}")
    return r.stdout.strip()


def top() -> str:
    return git("rev-parse", "--show-toplevel")


def slugify(title: str) -> str:
    s = re.sub(r"`[^`]*`", lambda m: m.group(0)[1:-1], title.lower())
    s = re.sub(r"\(.*?\)", "", s)
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return "-".join(s.split("-")[:6]) or "section"


def sort_key(num: str):
    m = re.match(r"3\.(\d+)([a-z]?)", num)
    return (int(m.group(1)), m.group(2))


# ---------- the index ----------

def sections(root: str):
    """[(number, title, filename)] from the section files, in order."""
    out = []
    for f in os.listdir(os.path.join(root, DIR)):
        m = FILE_RE.match(f)
        if not m:
            continue
        with open(os.path.join(root, DIR, f)) as fh:
            first = fh.readline().strip()
        title = re.sub(r"^#+\s*3\.\d+[a-z]?\s*", "", first)
        out.append((m.group(1), title, f))
    return sorted(out, key=lambda s: sort_key(s[0]))


def write_index(root: str) -> None:
    rows = [f"| [{n}]({f}) | {t} |" for n, t, f in sections(root)]
    body = "\n".join([
        "# PLAN-ros-alignment.md, section 3 -- one file per section",
        "",
        "Generated by `python tools/plan_section.py index`; do not edit by hand.",
        "A citation such as \"`PLAN-ros-alignment.md` 3.18\" means the file",
        "numbered 3.18 here. New sections: `python tools/plan_section.py new`",
        "(`docs/guides/PARALLEL-SESSIONS.md`).",
        "",
        SECTIONS_START,
        "| Section | Title |",
        "|---|---|",
        *rows,
        SECTIONS_END,
        "",
    ])
    with open(os.path.join(root, INDEX), "w") as fh:
        fh.write(body)


def cmd_index() -> None:
    root = top()
    write_index(root)
    print(f"{INDEX}: {len(sections(root))} sections")


# ---------- the one-time split ----------

def cmd_split() -> None:
    root = top()
    path = os.path.join(root, PLAN)
    lines = open(path).read().split("\n")
    starts = [i for i, l in enumerate(lines) if HEAD_RE.match(l)]
    end = next(i for i, l in enumerate(lines) if l.startswith("## 4."))
    if not starts:
        raise SystemExit("no ### 3.N sections left to split")
    os.makedirs(os.path.join(root, DIR), exist_ok=True)
    for k, s in enumerate(starts):
        e = starts[k + 1] if k + 1 < len(starts) else end
        m = HEAD_RE.match(lines[s])
        num, title = m.group(1), m.group(4)
        body = lines[s + 1:e]
        while body and body[-1] == "":
            body.pop()
        text = "\n".join([f"# {num} {title}", "",
                          f"*`PLAN-ros-alignment.md` section {num}; index: [README.md](README.md).*",
                          *body, ""])
        with open(os.path.join(root, DIR, f"{num}-{slugify(title)}.md"), "w") as fh:
            fh.write(text)
    pointer = [
        "### The sections live one per file",
        "",
        "Since 2026-10-07 each `3.N` section is its own file in",
        "`docs/plans/ros-alignment/`, indexed by",
        "[`ros-alignment/README.md`](ros-alignment/README.md), so parallel sessions",
        "never edit the same file (`docs/guides/PARALLEL-SESSIONS.md`). A citation",
        "\"`PLAN-ros-alignment.md` 3.18\" means `ros-alignment/3.18-*.md`. Start a",
        "new section with `python tools/plan_section.py new <slug> \"<title>\"`.",
        "",
    ]
    lines = lines[:starts[0]] + pointer + lines[end:]
    open(path, "w").write("\n".join(lines))
    write_index(root)
    print(f"split {len(starts)} sections into {DIR}/")


# ---------- reserving a number ----------

def used_numbers(root: str) -> set:
    nums = set()
    for ref in ("origin/dev", "HEAD"):
        listing = git("ls-tree", "--name-only", f"{ref}:{DIR}", check=False, cwd=root)
        for f in listing.splitlines():
            m = FILE_RE.match(f)
            if m:
                nums.add(int(m.group(2)))
    for b in git("branch", "-a", "--format=%(refname:short)", cwd=root).splitlines():
        m = BRANCH_RE.search(b)
        if m:
            nums.add(int(m.group(2)))
    return nums


def cmd_new(slug: str, title: str) -> None:
    root = top()
    slug = slugify(slug)
    git("fetch", "-q", "origin", cwd=root)
    n = max(used_numbers(root) | {0}) + 1
    for _ in range(20):
        num = f"3.{n}"
        branch = f"plan/{num}-{slug}"
        wt = os.path.join(root, ".claude", "worktrees", f"plan-{num}")
        r = subprocess.run(["git", "worktree", "add", "-q", "-b", branch, wt, "origin/dev"],
                           capture_output=True, text=True, cwd=root)
        if r.returncode == 0:
            break
        if "already exists" not in r.stderr:
            raise SystemExit(r.stderr.strip())
        n += 1                     # another session took it a moment ago
    else:
        raise SystemExit("could not reserve a section number")
    with open(os.path.join(wt, DIR, f"{num}-{slug}.md"), "w") as fh:
        fh.write(f"# {num} {title}\n\n"
                 f"*`PLAN-ros-alignment.md` section {num}; index: [README.md](README.md).*\n\n"
                 "**Why.** \n\n"
                 "**Criteria (written before building; CLAUDE.md section 7):**\n\n1. \n")
    write_index(wt)
    git("add", DIR, cwd=wt)
    git("commit", "-q", "-m", f"{num} reserved: {title}", cwd=wt)
    print(f"reserved {num} on branch {branch}\nworktree: {wt}\n")
    print(env_text(num))


# ---------- per-branch resources ----------

def section_of_branch(root: str) -> str:
    m = BRANCH_RE.search(git("rev-parse", "--abbrev-ref", "HEAD", cwd=root))
    if not m:
        raise SystemExit("not on a plan/3.N-* branch: pass the section, e.g. `env 3.44`")
    return m.group(1)


def resources(num: str) -> dict:
    """Everything a live stack can collide on, derived from the section
    number so no two sections share any of it (ports 9000 + 10 x minor)."""
    minor = int(num.split(".")[1].rstrip("abcdefghijklmnopqrstuvwxyz"))
    base = 9000 + 10 * (minor % 100)
    return {
        "PICAR_ROBOT_PORT": base, "PICAR_BRAIN_PORT": base + 1,
        "PICAR_BODY_PORT": base + 2, "PICAR_SENSOR_PORT": base + 3,
        "PICAR_SENSOR2_PORT": base + 4, "PICAR_BRIDGE_PORT": base + 5,
        # The minor number itself (3.44 -> 44): ROS 2 domains above 101 can
        # clash with Linux's ephemeral ports. 73 and 74 are the fixed domains
        # older stacks use (demo_explore's default, 3.42's lidar stack).
        "ROS_DOMAIN_ID": {73: 100, 74: 101}.get(minor % 100, minor % 100),
        "PICAR_ROS_CONTAINER": f"picar-ros-{num.replace('.', '')}",
        "ROS_IMAGE": f"vision-picar-ros:plan-{num}",
        "EXPLORE_LOGDIR": f"/tmp/vision-picar-{num}",
        "PICAR_ROBOT_URL": f"http://127.0.0.1:{base}",
        "PICAR_BRAIN_URL": f"http://127.0.0.1:{base + 1}",
        "PICAR_BRIDGE_URL": f"http://127.0.0.1:{base + 5}",
    }


def env_text(num: str) -> str:
    r = resources(num)
    lines = [f"# section {num}: paste into your shell, or `eval $(python tools/plan_section.py env)`"]
    lines += [f"export {k}={v}" for k, v in r.items()]
    lines.append(f"# build this branch's ROS image (never :latest): "
                 f"docker build -t {r['ROS_IMAGE']} service/slam && mkdir -p {r['EXPLORE_LOGDIR']}")
    return "\n".join(lines)


def cmd_env(num=None) -> None:
    print(env_text(num or section_of_branch(top())))


# ---------- overlap ----------

def changed(root: str, ref: str) -> set:
    base = git("merge-base", "origin/dev", ref, check=False, cwd=root)
    if not base:
        return set()
    return set(git("diff", "--name-only", base, ref, cwd=root).splitlines())


def cmd_overlap() -> None:
    root = top()
    git("fetch", "-q", "origin", cwd=root)
    me = git("rev-parse", "--abbrev-ref", "HEAD", cwd=root)
    mine = changed(root, "HEAD") - {INDEX}
    found = False
    for b in sorted(set(git("branch", "-a", "--format=%(refname:short)", cwd=root).splitlines())):
        if "plan/" not in b or b.endswith(me) or b == me:
            continue
        shared = sorted(mine & (changed(root, b) - {INDEX}))
        if shared:
            found = True
            print(f"{b}:\n  " + "\n  ".join(shared))
    if not found:
        print("no file this branch changes is changed on another plan/* branch")


# ---------- the merge gate ----------

def gate_dir() -> str:
    d = os.path.join(git("rev-parse", "--git-common-dir"), "plan-gate")
    os.makedirs(d, exist_ok=True)
    return d


# The push gate runs a FAST tier, not the full suite (user, 2026-10-09: a
# 40-minute run on every push was too heavy, and a pass named one commit, so
# every rebase onto another session's push started it over). Left out, and
# run nightly by tools/nightly_suite.sh and by `ready --full`:
#   * the real-browser and live-stack tests -- slow and timing-sensitive;
#   * the measurement SWEEPS -- hundreds of simulated missions or runs that
#     pin a phase's acceptance numbers. Timed 2026-10-09, these files held
#     ~45 of the 51 minutes. Their quick neighbours (test_depth_veto,
#     test_pivot_safety, test_authority, test_failsafes, the contracts) stay.
SLOW_FILES = [
    "test_arrival.py", "test_bearing_turns.py", "test_firmware_fork.py",
    "test_footprint_safety.py", "test_guarded_verbs.py", "test_inventory_mission.py",
    "test_lidar_safety.py", "test_pan_safety.py", "test_ros_driver_board.py",
    "test_ros_verb_safety.py", "test_settle_pass.py", "test_speed_clearance.py",
    "test_startup_race.py", "test_wheel_feedback.py",
]
SLOW_TESTS = [
    "--ignore-glob=tests/test_ui*.py",
    "--ignore=tests/test_frame_source.py",
    "--ignore-glob=tests/*_live.py",
    *[f"--ignore=tests/{f}" for f in SLOW_FILES],
]


def docs_only(paths) -> bool:
    """A change no test reads: prose, specs and the plan. The spec lint
    still runs on it."""
    return bool(paths) and all(
        p.endswith(".md") or p.startswith(("docs/", "docs-review/")) for p in paths)


def venv_python(root: str) -> str:
    py = os.path.join(os.path.dirname(git("rev-parse", "--git-common-dir", cwd=root)), ".venv", "bin", "python")
    return py if os.path.exists(py) else sys.executable


# Git exports its repository-local variables (GIT_DIR and friends) to a
# hook, and every git command a child runs then acts on THIS repository,
# whatever its cwd. The pre-push hook runs the suite, and a test that builds
# a scratch repo in tmp_path (test_plan_section.py) re-initialised this one
# on 2026-10-09: core.bare=true, a "t" identity, a "base" commit on the
# branch being pushed, a stray branch. The list is git's own
# (`git rev-parse --local-env-vars`), less GIT_CONFIG_COUNT: with
# GIT_CONFIG_KEY_n/VALUE_n it carries config the environment itself
# injects (the cloud git proxy's), not a pointer to a repository.
_LOCAL_GIT_VARS_FALLBACK = (
    "GIT_ALTERNATE_OBJECT_DIRECTORIES", "GIT_CONFIG", "GIT_CONFIG_PARAMETERS",
    "GIT_OBJECT_DIRECTORY", "GIT_DIR", "GIT_WORK_TREE", "GIT_IMPLICIT_WORK_TREE",
    "GIT_GRAFT_FILE", "GIT_INDEX_FILE", "GIT_NO_REPLACE_OBJECTS",
    "GIT_REPLACE_REF_BASE", "GIT_PREFIX", "GIT_SHALLOW_FILE", "GIT_COMMON_DIR",
)
_KEEP_GIT_VARS = {"GIT_CONFIG_COUNT"}


def repo_local_git_vars() -> tuple:
    try:
        out = subprocess.run(["git", "rev-parse", "--local-env-vars"], cwd="/",
                             capture_output=True, text=True, timeout=10).stdout.split()
    except (OSError, subprocess.SubprocessError):
        out = []
    return tuple(v for v in (out or _LOCAL_GIT_VARS_FALLBACK) if v not in _KEEP_GIT_VARS)


def scrubbed_env() -> dict:
    """This process's environment, minus the variables that would point a
    child's git commands at this repository."""
    drop = set(repo_local_git_vars())
    return {k: v for k, v in os.environ.items() if k not in drop}


def run_tests(root: str, full: bool) -> bool:
    args = [] if full else SLOW_TESTS
    return subprocess.run([venv_python(root), "-m", "pytest", "tests/", "-q",
                           "-p", "no:cacheprovider", *args], cwd=root,
                          env=scrubbed_env()).returncode == 0


def change_id(base: str, sha: str, root: str) -> str:
    """`git patch-id` of the change being pushed: the same diff gets the same
    id after a rebase that applied cleanly. Keying the pass on this, not on
    the commit, is what stops a 7-minute tier losing a race to every other
    session's push (2026-10-09: two in a row). The nightly full run still
    sees how changes combine."""
    diff = subprocess.run(["git", "diff", base, sha], capture_output=True, cwd=root).stdout
    out = subprocess.run(["git", "patch-id", "--stable"], input=diff,
                         capture_output=True, cwd=root).stdout.decode().split()
    return "change-" + out[0] if out else ""


def cmd_gate(base: str, sha: str) -> None:
    """Called by tools/hooks/pre-push for a push of `sha` to dev."""
    root = top()
    # Once, where the hook's GIT_DIR enters: every child from here on (the
    # spec lint, the fast tier, anything added later) inherits a clean
    # environment. Our own git calls below pass cwd=root, so need none.
    clean = scrubbed_env()
    os.environ.clear()
    os.environ.update(clean)
    if os.path.exists(os.path.join(gate_dir(), sha)):
        return
    cid = change_id(base, sha, root) if base else ""
    if cid and os.path.exists(os.path.join(gate_dir(), cid)):
        print("pre-push: this change already passed the fast tier before a rebase", flush=True)
        return
    files = git("diff", "--name-only", base, sha, cwd=root).splitlines() if base else []
    if docs_only(files):
        print("pre-push: docs only -- running the spec lint", flush=True)
        if subprocess.run([venv_python(root), "-m", "pytest", "tests/test_spec_lint.py",
                           "-q", "-p", "no:cacheprovider"], cwd=root,
                          env=scrubbed_env()).returncode:
            raise SystemExit("pre-push: spec lint failed")
        return
    if sha != git("rev-parse", "HEAD", cwd=root) or git(
            "status", "--porcelain", "--untracked-files=no", cwd=root):
        raise SystemExit("pre-push: the fast tier runs on the working tree, so push "
                         "HEAD with everything committed (or run `ready` first)")
    print(f"pre-push: running the fast tier on {sha[:9]} ...", flush=True)
    if not run_tests(root, full=False):
        raise SystemExit("pre-push: fast tier failed")
    for key in (sha, cid):
        if key:
            open(os.path.join(gate_dir(), key), "w").write("passed fast\n")


def cmd_ready(full: bool = False) -> None:
    root = top()
    git("fetch", "-q", "origin", cwd=root)
    if subprocess.run(["git", "merge-base", "--is-ancestor", "origin/dev", "HEAD"], cwd=root).returncode:
        raise SystemExit("not rebased on origin/dev: `git rebase origin/dev` first")
    nums = [n for n, _, _ in sections(root)]
    dup = {n for n in nums if nums.count(n) > 1}
    if dup:
        raise SystemExit(f"duplicate section numbers: {sorted(dup)}")
    write_index(root)
    if git("status", "--porcelain", "--", INDEX, cwd=root):
        raise SystemExit(f"{INDEX} is stale: commit the regenerated index")
    if git("status", "--porcelain", "--untracked-files=no", cwd=root):
        raise SystemExit("uncommitted changes: commit first, so the pass names a commit")
    sha = git("rev-parse", "HEAD", cwd=root)
    print(f"running the {'full suite' if full else 'fast tier'} on {sha[:9]} ...", flush=True)
    if not run_tests(root, full):
        raise SystemExit("suite failed: no pass recorded")
    open(os.path.join(gate_dir(), sha), "w").write("passed full\n" if full else "passed fast\n")
    print(f"recorded a pass for {sha[:9]}; a push of this commit to dev may go ahead")


def main(argv):
    if not argv:
        raise SystemExit(__doc__)
    cmd, args = argv[0], argv[1:]
    if cmd == "new" and len(args) == 2:
        cmd_new(*args)
    elif cmd == "env":
        cmd_env(*args[:1])
    elif cmd == "index":
        cmd_index()
    elif cmd == "overlap":
        cmd_overlap()
    elif cmd == "ready":
        cmd_ready(full=args[:1] == ["--full"])
    elif cmd == "gate" and len(args) == 2:
        cmd_gate(*args)
    elif cmd == "split":
        cmd_split()
    else:
        raise SystemExit(__doc__)


if __name__ == "__main__":
    main(sys.argv[1:])
